sudo: true
language: php
php:
  - 7.0
  - 5.6
  - 5.5
before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev --no-interaction
script:
  - php vendor/bin/phpunit -c phpunit.xml.dist
  - php coverage-checker.php build/logs/clover.xml 100
after_script:
  - php vendor/bin/coveralls -v